---
abstract: 'Client for 1-wire File System server'
author:
  - 'Mark Hindess <soft-cpan@temporalanomaly.com>'
build_requires:
  AnyEvent::MockTCPServer: 0
  English: 0
  Exporter: 0
  File::Temp: 0
  Test::More: 0
configure_requires:
  ExtUtils::MakeMaker: 6.31
dynamic_config: 0
generated_by: 'Dist::Zilla version 4.200004, CPAN::Meta::Converter version 2.101670'
license: perl
meta-spec:
  url: http://module-build.sourceforge.net/META-spec-v1.4.html
  version: 1.4
name: AnyEvent-OWNet
requires:
  AnyEvent: 0
  AnyEvent::Handle: 0
  AnyEvent::Socket: 0
  Carp: 0
  Sub::Name: 0
  Try::Tiny: 0
  constant: 0
  perl: 5.008
resources:
  bugtracker: https://github.com/beanz/anyevent-ownet-perl/issues
  homepage: http://search.cpan.org/dist/AnyEvent-OWNet/
  repository: git://github.com/beanz/anyevent-ownet-perl.git
version: 1.111950
